---
- name: Stop the scanner service
  systemd:
    state: stopped
    name: 'xroad-scanner'

- name: Remove the script file
  file:
    path: '/tmp/server.py'
    state: absent

- name: Uninstall the scanner service
  file:
    path: '/etc/systemd/system/xroad-scanner.service'
    state: absent
